world_size: 1

patchify:
  is_enabled: false

mlp:
  is_enabled: false

attn:
  # debug: true
  is_enabled: false
  # coverage: 0.7
  top_keys: 0.05
  random_keys: 0.01
  # top_keys: 0
  # random_keys: 0
  # Number of local voxels to use for static local attention
  local_voxels: 0
  local_1d_window: 0
  # local_1d_window: 0.25
  first_n_dense_layers: 2
  recompute_mask: true
  should_compress_indices: true

  # If schedule is not None, will override full_step_every
  full_step_schedule: !!set
    ? 0
    ? 1
    ? 10
    ? 40
  # full_step_every: 3

  # Do not change below this line -- kernel-specific business
  pad_qkv_before_kernel: true

offloading:
  mlp.out_cache: true
  attn.out_cache: true
  attn.indices: false
  text_encoders: true

tea_cache:
  is_enabled: false
  threshold: 0.06
  debug: false

token_cache:
  is_enabled: true
  cache_ratio: 0.85
  full_every: 3

step_caching:
  is_enabled: false
  # Feel free to play with this -- it's pretty stable across different schedules!
  skip_step_schedule: !!set
    ? 7
    ? 11
    ? 13
    ? 14
    ? 15
    ? 17
    ? 18
    ? 19
    ? 21
    ? 22
    ? 23
    ? 25
    ? 26
    ? 27
    ? 29
    ? 31
    ? 33
    ? 34
    ? 35
    ? 37
    ? 38
    ? 39
    ? 41
    ? 42
    ? 43
