patchify:
  is_enabled: false
  # To disable patching at any level, set that level's patch size to 1. To disable patching entirely, set all patch sizes to 1.
  chunk_size_1: 2
  chunk_size_2: 2

attn:
  is_enabled: false
  top_keys: 0.2

  full_step_every: 10
  first_n_dense_layers: 2
  recompute_mask: false
  should_compress_indices: false
  # do not change below this line
  counts_multiple_of: 112
  pad_qkv_before_kernel: false

step_caching:
  is_enabled: true
  # Feel free to play with this -- it's pretty stable across different schedules!
  skip_step_schedule: !!set
    ? 7
    ? 11
    ? 13
    ? 14
    ? 15
    ? 17
    ? 18
    ? 19
    ? 21
    ? 22
    ? 23
    ? 25
    ? 26
    ? 27
    ? 29
    ? 31
    ? 33
    ? 34
    ? 35
    ? 37
    ? 38
    ? 39
    ? 41
    ? 42
    ? 43

offloading:
  global_disable_offloading: true
