attn:
  counts_multiple_of: 128
  coverage: null
  debug: false
  first_n_dense_layers: 2
  full_attn_from_3d_tail: false
  full_attn_to_3d_tail: false
  full_step_every: 1
  full_step_schedule: null
  is_enabled: false
  local_1d_window: 0
  local_voxels: 0
  mbm: 192
  pad_qkv_before_kernel: true
  random_keys: 0.01
  recompute_mask: false
  should_compress_indices: true
  top_keys: 0.0
generation_index: 0
height: 820
mlp:
  block_mask_cache: 0
  bm: 128
  counts_multiple_of: 256
  first_n_dense_layers: 2
  full_step_every: 1
  is_enabled: false
  is_fp8: false
  mbm: 0
  random_keys: 0
  top_keys: 0
model_name: hunyuan
num_model_invocations_per_inference_step: 1
offline_search:
  is_enabled: false
  output_path: offline-search.json
offloading:
  attn.counts: false
  attn.indices: true
  attn.lse_constants: false
  attn.out_cache: true
  global_disable_offloading: true
  mlp.blockmean_mid_cache: false
  mlp.counts: false
  mlp.indices: false
  mlp.out_cache: false
  mlp.sparse_act_T: false
  text_encoders: true
patchify:
  chunk_size_1: 8
  chunk_size_2: 4
  is_enabled: false
should_profile: false
step_caching:
  is_enabled: false
  skip_step_schedule: []
steps: 50
tea_cache:
  debug: true
  is_enabled: true
  threshold: 0.65
token_cache:
  cache_ratio: 0.85
  full_every: 3
  is_enabled: false
  max_text_len: 256
width: 1280
world_size: 8
