mlp:
  is_enabled: false
  is_fp8: true
  top_keys: 0.3
  
  random_keys: 0.05
  full_step_every: 10
  block_mask_cache: 2
  first_n_dense_layers: 2
  # do not change below this line
  counts_multiple_of: 256
  bm: 128
  mbm: 128

patchify:
  is_enabled: false
  # To disable patching at any level, set that level's patch size to 1. To disable patching entirely, set all patch sizes to 1.
  chunk_size_1: 8
  chunk_size_2: 4

attn:
  is_enabled: false
  top_keys: 0.165

  full_step_every: 10
  full_step_schedule: ~
  first_n_dense_layers: 2
  recompute_mask: false
  should_compress_indices: false
  # do not change below this line
  counts_multiple_of: 112
  pad_qkv_before_kernel: false
  mbm: 192

offloading:
  global_disable_offloading: true
  mlp.out_cache: false
  mlp.indices: false
  mlp.counts: false
  mlp.sparse_act_T: false
  mlp.blockmean_mid_cache: false
  attn.out_cache: false
  attn.indices: false
  attn.counts: false
  attn.lse_constants: false
  text_encoders: false
