mlp:
  is_enabled: true
  is_fp8: false
  top_keys: 0.3
  random_keys: 0.05
  full_step_every: 10
  block_mask_cache: 2
  first_n_dense_layers: 2

attn:
  is_enabled: true
  top_keys: 0.165
  full_step_every: 10
  first_n_dense_layers: 2
  recompute_mask: false
  should_compress_indices: false

patchify:
  # To disable patching at any level, set that level's patch size to 1. To disable patching entirely, set all patch sizes to 1.
  chunk_size_1: 8
  chunk_size_2: 4
